## The function makeCacheMatrix puts in practice the concept of lexical scoping.
## The main goal is to pass a matrix as argument and use the function solve() to
## calculate its inverse. The magic appears when we are able to generate an object
## that contains the setters and getters and its context is visible in the global
## environment by the function cacheSolve.

makeCacheMatrix <- function(x = matrix()) {
        s <- NULL
        set <- function(y) {
                x <<- y
                s <<- NULL
        }
        get <- function() x
        setinverse <- function(solve) s <<- solve
        getinverse <- function() s
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
        
}

## The function cacheSolve receives as argument the same object generated by 
## makeCacheMatrix. It prints the latest calculated inverse matrix, if the 
## original matrix wasn't changed.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        s <- x$getinverse()
        if(!is.null(s)) {
                message("getting cached data")
                return(s)
        }
        data <- x$get()
        s <- solve(data, ...)
        x$setinverse(s)
        s
}
